name: operation-grandson
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flask
  - flask-cors
  - pip:
      - langflow
      - langchain
      - openai
      - pydantic
      - aiohttp
      - typing-extensions
      - uvicorn